version: '3.2'

services:
  document-api:
    image: document-api
    build:
      context: document-api/
      dockerfile: ./Dockerfile
 
  document-api-test:
    image: document-api-test
    build:
      context: .
      dockerfile: document-api.Tests/Dockerfile
