version: 2.1

commands:
  build-and-run-tests:
    description: "Builds the project and runs its tests"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build
          command: docker-compose build document-api-test
      - run:
          name: Run tests
          command: docker-compose up document-api-test

jobs:
  build-and-check:
    docker:
      - image: circleci/python:3.7
    steps:
      - build-and-run-tests

workflows:
  check:
      jobs:
      - build-and-check
